channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-ggpubr
  - r-rstatix
  - r-datarium
  - r-emmeans
  - bioconductor-phyloseq
  - bioconductor-deseq2
